export interface IData {
  "odata.type": string;
  "odata.id": string;
  "odata.etag": string;
  "odata.editLink": string;
  FileSystemObjectType: number;
  FileLeafRef: string;
  FileRef: string;
  EncodedAbsUrl: string;
  Id: number;
  ServerRedirectedEmbedUri: null | string;
  ServerRedirectedEmbedUrl: string;
  ContentTypeId: string;
  OData__ColorTag: null;
  ComplianceAssetId: null;
  Title: null | string;
  Process: string;
  Subprocess: string;
  "Last Updated": string;
  sample: string;
  Location: string;
  "SOP Version": string;
  "Approved by": string;
  Nature: string;
  ID: number;
  Created: string;
  AuthorId: number;
  Modified: string;
  EditorId: number;
  OData__CopySource: null;
  CheckoutUserId: null;
  OData__UIVersionString: string;
  GUID: string;
}
